### ISSUE TITLE
The Smooth Gecko Project

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#334]
### Improve the handoff from recording in Gecko to viewing in devtools. 

- [ ] After recording, Gecko should target a new tab, not reuse the same one #326 
- [ ] Uploading sourcemaps should not block creating the recording id #351
- [ ] Initial page load can take awhile #352
- [ ] While uploading the URL bar is wrong #330
- [ ] Improve cancel recordings flow #232
- [ ] The right-click menu on tabs is rendering badly #226
- [ ] Other items probably?

### There is some ambiguous logic while recording

* Clicking the refresh button currently makes the screen go white
* Navigating via the URL bar cancels the recording #289
* Navigating via back / forward buttons continues recording
* Clicking a link continues recording
* Command clicking a link opens a new tab that is not recorded

Ideally we would be consistent and continue recording or start a new recording 

- [ ] clicking refresh should either continue recording or start a new recording
- [ ] Navigating via the URL bar should either continue recording or start a new recording #289
- [x] Navigating via back / forward buttons continues recording
- [x] Clicking a link continues recording
- [ ] Command clicking a link should open a new tab that is recording

### Show better error messages when issues occur 

- [ ] show error message explaining why the region has gone white #305
- [ ] Add clearer error messages for web apis #314
- [ ] Improve recording error page #191
- [ ] Improve error handling when recording process can't connect to dispatcher #179

**Comment by jonbell-lot23** [comment]
Assigning to Jason for discussion, prioritisation, and assignment to the right person

**Comment by jasonLaster** [comment]
Talking to alex from replit. It'd be nice to reduce some daily-use friction around using replay as the default browser for testing

Things like: refreshing, navigating etc.

**Comment by jonbell-lot23** [comment]
Indeed! There's a grab bag of things but a good place to start is https://github.com/RecordReplay/gecko-dev/issues/326. Can we prioritise that next week?

**Comment by jasonLaster** [comment]
split this into several smaller projects
