### ISSUE TITLE
Improve browser usability

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#348]
### Starting a recording
~Initial page load can take awhile to load #352~ _tracked by #392_

### Saving a recording

- [x] After recording, Gecko should target a new tab, not reuse the same one #326 
- [x] Uploading sourcemaps should not block creating the recording id #351
- [x] While uploading the URL bar is wrong #330
- [x] Improve cancel recordings flow #232
- [ ] Add a replay upload error screen #368 

### General 
- [x] Replay does not appear in the Present window display for google meet #312
- [x] Add "New Tab" #241
- [x] The right-click menu on tabs is rendering badly #226
- [x] Updated Replay browser tells me to update #250

**Comment by jasonLaster** [comment]
@jonbell-lot23 how is 2 different from 3?

**Comment by jonbell-lot23** [comment]
> @jonbell-lot23 how is 2 different from 3?

I see a list of items, not sure what you're referring to

**Comment by ryanjduffy** [comment]
> The record button should deep link and open the replay browser

@jonbell-lot23 - Is the last item still required? I'm not sure to which button this comment is referring.

**Comment by jonbell-lot23** [comment]
@ryanjduffy Ah, yes. Here's a ticket that explains more: https://github.com/RecordReplay/devtools/issues/2688
