### ISSUE TITLE
Replay branding (v1)

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#350]
When users are recording they should feel like they are using Replay.

### Remove Firefox branding

* [x] Firefox brand copy should not leak in through settings, crashes, and other UI
* [x] Launching two versions of Replay #373 
* [ ] disable firefox accounts #331
* [x] Don't show firefox release notes #268
* [x] "unable to connect" page says firefox instead of replay #238
* [x] "Welcome to Firefox" message is confusing #288
* [ ] Remove unwanted features

### Firefox Branding we can't repro 

* [ ] Firefox version updates should not appear
* [ ] Firefox copy is sometimes missing #252 

### Replay chrome

The browser chrome is a great opportunity to unify the Replay browser, DevTools, and larger brand which will help the product feel more cohesive. 

- [x] Adopt AplenGlow as the default Replay Theme #370
- [ ] Create a new Replay theme 

<img width="1527" alt="Screen Shot 2021-05-10 at 11 03 57 AM" src="https://user-images.githubusercontent.com/254562/117704285-84171400-b17f-11eb-8c81-cc5f3f95bbb0.png">

**Comment by jasonLaster** [comment]
@ryanjduffy i'm closing this since it's basically done. We'll likely create a V2 with a more focused list
