### ISSUE TITLE
Show better error messages when issues occur 

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#354]
Replay should more gracefully handle issues that occur while recording

- [x] show error message explaining why the region has gone white #305
- [x] Add clearer error messages for web apis #314
- [x] Improve recording error page #191
- [ ] Improve error handling when recording process can't connect to dispatcher #179

**Comment by bhackett1024** [comment]
This is in the GTM doc but managed to slip off the planning board.  It would be good to get something working this week so that we can message users when the page they are viewing is using disabled features like video, streaming wasm, etc.
