### ISSUE TITLE
Improve onboarding

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#360]
We should look into ways we can improve the onboarding experience

### Getting Setup 

- [ ]  Replay does not install for security reasons #240 
- [ ]  Disable popup blockers for replay.io #313
- [ ] Investigate importing settings from other browsers #323

### Usability

- [ ] Clicking record from Replay should ask if you're sure (low priority)
- [ ] Clicking record should ask if it's ok to reload the page (#339)

**Comment by jonbell-lot23** [comment]
See https://github.com/RecordReplay/gecko-dev/issues/366
