### ISSUE TITLE
Onboarding: Creating a recording

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#366]
We should look into ways we can improve the onboarding experience

### Getting Setup 

- [x] Add Welcome screen #361
- [x] Add New Tab #241
- [x] Investigate importing settings from other browsers #323
- [x]  Disable popup blockers for replay.io #313

### Nice to haves
- [x] the install finder window should be branded #337 
- [ ] Clicking record should ask if it's ok to reload the page (#339)
- [ ]  Replay does not install for security reasons #240

**Comment by jasonLaster** [comment]
closing this project so we can track import setting separately
